### ISSUE TITLE
Backend: Map app w dedicated, simplified variants of stats charts

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaDataService#181]
another issue im filing based on slack discussion so the thought isnt lost. Its very possible the first go of mapveu will feature a limited set of stats charts rather than the full suite of them, or that the stats charts we offer may not support all the configurations of the full eda variant (ex: no trend lines in scatter maybe, for perf reasons). I also think itd be confusing to offer a map viz in a map based app? so im anticipating adding a map app that explicitly lists what stats charts are available w what configurations for the vectorbase project. maybe we can use this issue as a platform for discussion around what all stats charts we need w what configurations as well prior to implementing.

**Comment by bobular** [comment]
The MapVEu client could just use the existing chart data endpoints, and manually add viewport and selected marker (which will be a `geohash_3 IN [ 'abc', 'abd', 'abe' ]` type query for now) filters rather than use special viewport parameters.

However, if complete cases and other stats are a waste of compute, it might make sense to remove them.

To start with we could have histogram, barplot, boxplot and lineplot (haha, that's nearly all of them!)

**Comment by d-callan** [comment]
possible duplicate, resolved.
