### ISSUE TITLE
Apps: overlay in beta div doesn't limit to the appropriate entities

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/EdaDataService#246]
Also may affect other apps, not sure

@d-callan do you happen to have an example? When i checked the few i looked at seemed okay

**Comment by d-callan** [comment]
Well I guess the question is what do you want it to look like for the computed vars? Right now computed vars don't make their way into the dependency order, on the assumption that the entire defined order in turn depends on the computed vars. That is maybe an assumption that we should reconsider?

**Comment by dmfalke** [comment]
It's worth discussing. If we're certain about this assumption, then we should just implement that in the client. Otherwise, the data service should probably specify it, explicitly. I'm curious if the order would ever change between apps? Could this value be the same for all scatter plots, regardless of app?

**Comment by asizemore** [comment]
after talking with @d-callan , we'll mark this for b63. We'll confirm at the next mbio meeting.

**Comment by asizemore** [comment]
Reminder for prioritization - this currently affects 4 studies (the four studies that have multiple assay branches)

**Comment by danicahelb** [comment]
QA paused until compute service is working again

**Comment by asizemore** [comment]
CS is up and running. Ready for QA! (please qa the live site at this point :) )
