### ISSUE TITLE
Backend: Variable constraints for categorical axes should limit values to something legible

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaDataService#69]
we have a constraint specified in the data service for overlay vars for ex, so that they cant have more than 8 values since we only have 8 colors in our qualitative palette. do we need something similar for categorical axes (bar and box plot xaxis, mosaic plot both axes as examples)? and if so what should the max number of values be?

aside: i wanted a question label for this. it looks like there should be one, but i couldnt select it..

**Comment by danicahelb** [comment]
@steve-fischer-200 please cost this out

**Comment by d-callan** [comment]
on the backend this should be pretty trivial to do, if we know what value wed like to set the limit to.. sort of related, idk if the client is actually using the constraints based on number of values yet.

**Comment by d-callan** [comment]
think ive sort of arbitrarily set it to 10 for now in most places. can change this when we decide what wed like but for veupathdb/edadataservice#87 i needed a limit before removing the constraint on categorical data shape

**Comment by danicahelb** [comment]
@d-callan I think 10 is a good starting point for us to roll out for feedback. Can you confirm that all "categorical" axes are limited to variable with 10 or fewer unique values (in the whole dataset, not in the whole subset)

**Comment by d-callan** [comment]
Yes. This is probably being deployed soon, if not already.

**Comment by danicahelb** [comment]
9/13/2021 EDA WG meeting confirmed that 10 is a good starting point for phase 1. We will need to check (1) how value labels are impacted & (2) how the plotted data is impacted.

Ann indicated that microbiomeDB will want to graph "top 10", further confirming that 10 is a good starting point

**Comment by nkittur-uga** [comment]
SCORE S. mansoni Cluster Randomized Trial- _Occupation_ has dozens of values and is not available in boxplot (x), barplot and rxc. 

GEMS1 variable _Caregiver relationship to participant_ which has >10 values is not available in barplot and rxc. 

_Interviewee's relationship to participant_, which has exactly 10 values, is not available in rxc, and it should be, if the limit is 10. 
Boxplot with _Interviewee's relationship to participant_ 
gives this error:
500 Internal Server Error {"status":"server-error","message":"Unable to fetch all required data","requestId":"1DPD3IdCC9kcnOZQV8mPMD"}

So this issue is overall OK but needs to be checked for vars with exactly 10 values.

**Comment by danicahelb** [comment]
paused until GEMS1 is on EDA

**Comment by danicahelb** [comment]
@nkittur-uga please revisit this ticket now that GEMS1 has been reloaded

**Comment by nkittur-uga** [comment]
GEMS1 variable _Interviewee's relationship to participant,_ which has exactly 10 values, is now available in categorical axis. QA is complete.
