### ISSUE TITLE
Unable to use ordinal variables as categorical variable in overlay

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/EdaDataService#83]
Identified by @bobular. Using PRISM2 ICEMR cohort, he tried to use "Acres categorization" (a household variable) as an overlay variable and found that an empty plot appeared. The plot appears correctly if you use a categorical variable that's not ordinal, like "Bank account"
![Screen Shot 2021-09-03 at 11 09 47 AM](https://user-images.githubusercontent.com/54597319/132035742-e76cd4eb-46d7-45f2-a204-d88f436e9308.png)

**Comment by d-callan** [comment]
similar to veupathdb/edasubsettingservice#19 .. think the problem is the variable vocabulary claims things like ">3" and then gives actual values like "4. >3". the response from the data service succeeds and is accurate given what it was provided in any case. and the variable vocabulary seems fine to me. the values there are the ones i imagine wed like to display, and in the proper order. think this may be for @steve-fischer-200 and the subsetting service?

**Comment by d-callan** [comment]
to be clear, i dont think the values need to have the numbers indicating order in front of them, so long as the vocabulary is known to be properly ordered.

**Comment by bobular** [comment]
This seems fixed now?

![image](https://user-images.githubusercontent.com/308639/133074756-7d8248d2-86c8-4091-b91d-99b298902ed9.png)


histogram endpoint is now returning `>3`  not `4: >3`

```
{"overlayVariableDetails":
  {"variableId":"EUPATH_0020221",
   "entityId":"PCO_0000024",
   "value":">3"
  }
}
```

**Comment by SheenaTomko** [comment]
Yes, looks fixed. I'm closing it
